# Generated by Django 6.0.6 on 2026-06-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='full_series',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='series',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_types', to='yugioh.cardtype'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='frame_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_types', to='yugioh.frametype'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='monster_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster_attributes', to='yugioh.monsterattribute'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='monster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster_types', to='yugioh.monstertype'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monsterattribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PrintSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='yugioh.carddetails')),
                ('full_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='yugioh.series')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='yugioh.rarity')),
            ],
        ),
    ]
